cloudtrail_bucket_name=<cloud_trail_bucket_name>
ciem_cloudtrail_account_role_name=mciem-cloudtrail-account-role
ciem_oidc_provider_role_name=mciem-oidc-provider-role
oidc_provider_account_id=<account_id_where_oidc_role_is_created>
tenant_id=<tenant_id>
